[build]
  command = "node ./create-env.js && npm run generate"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  NITRO_PRESET = "netlify-static"

[functions]
  directory = "netlify/functions"
